### ISSUE TITLE
Incorrect total count

### ISSUE THREAD

**Issue by yvza** [bokub/github-stats-box#2]
Hallo,

i have already switching ALL_COMMITS: false and ALL_COMMITS: true but the result is wrong

the result show 200++, but in total it should be 1k++

repository is right [here](https://github.com/yvza/github-stats-box/)

**Comment by bokub** [comment]
Can you [generate a new token](https://github.com/settings/tokens/new) with **repo** and **gist** scopes, and replace you `GH_TOKEN` secret with this new token?

I think the `repo` scope is needed to count private contributions

**Comment by yvza** [comment]
woaaa its work now, and i see 3 hours ago u update the readme.md

thanks 😄
